### PR TITLE
chore: change v2alpha1 SubNamespace status to kstatus-compatible subresource

### PR DESCRIPTION
**Pull request by erikgb**
A new and currently unserved API version was added with https://github.com/cybozu-go/accurate/pull/101. This PR makes `status` in the new version a subresource compatible with [kstatus](https://github.com/kubernetes-sigs/cli-utils/blob/master/pkg/kstatus/README.md).

I have also added conversion code with unit tests, so you can get an idea of how I plan to move forward after this is (hopefully) merged. The next steps will probably be:

1. Add conversion webhook using the conversion logic established in this PR.
2. Make `v2alpha1` served, migrate controller to reconcile `v2alpha1` and make `v2alpha1` the storage version.

I would prefer using SSA when updating `status` from controller in the latter step. Please let me know what you think! This is probably best done by generating apply-configurations in a separate pre-PR.

Relates to  https://github.com/cybozu-go/accurate/issues/85

NOTE: The proposed fuzz conversion tests added in this PR are highly inspired by the equivalent test setup in https://github.com/kubernetes-sigs/cluster-api. Example: https://github.com/kubernetes-sigs/cluster-api/blob/main/api/v1alpha4/conversion_test.go

### CODE REVIEW

**Comment by erikgb** [comment]
If you want, I can split this PR:

1. Establish the new API version as a copy of v1
2. Make the new version compatible with kstatus

**Comment by erikgb** [comment]
I have now created a dedicated PR for (just) introducing the new API version: https://github.com/cybozu-go/accurate/pull/101

**Comment by erikgb** [comment]
@zoetrope @ymmt2005 I think this PR is ready for a round of review now. Please let me know what you think!

**Review by zoetrope — APPROVED** [review]
Thank you for the excellent pull request!
I believe the PR looks great.

I wasn't familiar with the "kstatus" library before, but it looks interesting. 
In situations like this, I often use [apimachinery's Condition](https://github.com/kubernetes/apimachinery/blob/master/pkg/api/meta/conditions.go).

**Comment by erikgb** [comment]
> Thank you for the excellent pull request! I believe the PR looks great.
> 
> I wasn't familiar with the "kstatus" library before, but it looks interesting. In situations like this, I often use [apimachinery's Condition](https://github.com/kubernetes/apimachinery/blob/master/pkg/api/meta/conditions.go).

Thanks for the nice feedback, @zoetrope! We are also heavy users of [apimachinery's Condition](https://github.com/kubernetes/apimachinery/blob/master/pkg/api/meta/conditions.go) in our operators not yet migrated to SSA. I think the utilities in this package are mostly useful with CSA. But we will get to that in the follow-up PRs. 😉

**Comment by erikgb** [comment]
Is there anything more needed to get this merged?

**Pull request merged**
