### PR TITLE
build(deps): bump Kubernetes to 1.30

### PR DESCRIPTION
**Pull request by erikgb**
This PR bumps Kubernetes to 1.30, ref. https://cybozu-go.github.io/accurate/maintenance.html#how-to-update-supported-kubernetes

### CODE REVIEW

**Comment by erikgb** [comment]
I am still waiting for a 1.30 image of [kindest/node](https://hub.docker.com/r/kindest/node/tags?page=&page_size=&ordering=&name=1.30) to be available before setting this PR ready for review.

But the aqua setup seems borked again. Can you take a look @yamatcha?

**Comment by zoetrope** [comment]
@erikgb 
aqua updated. Please rebase to main branch.

**Comment by erikgb** [comment]
> @erikgb aqua updated. Please rebase to main branch.

@zoetrope Thanks! Works a lot better now! Do you mind reviewing https://github.com/cybozu-go/accurate/pull/126 while we are waiting for kindest/node 1.30.x image?

**Comment by erikgb** [comment]
This PR should be ready for review now! After it's merged, we should be able to finalize the migration to SSA. We are missing upgrade of SubNamespace status managedFields. Not extremely important, but will allow for even cleaner resources.

**Review by zoetrope — APPROVED** [review]
LGTM

**Pull request merged**
